# Site Settings
title: Parallax Pal
description: A showcase of modern web development featuring parallax scrolling effects
baseurl: ""
url: ""

# Navigation
nav_items:
  - title: Home
    url: /
  - title: Projects
    url: /projects
  - title: About
    url: /about
  - title: Contact
    url: /contact

# Features Section
features:
  - title: Smooth Parallax Effects
    description: Optimized scrolling animations that respond naturally to user interaction
    icon: layer-group
    
  - title: Responsive Design
    description: Seamlessly adapts to any screen size while maintaining performance
    icon: mobile-alt
    
  - title: Modern Web Stack
    description: Built with cutting-edge web standards and progressive enhancement
    icon: code

# Remove iOS-specific configurations
markdown: kramdown
